### ISSUE TITLE
npn install Ubuntu 18.04 -> node-pre-gyp ERR! Tried to download(404):

### ISSUE THREAD

**Issue by carlesgutierrez** [MaxusDev/WelleAPI#14]
I'm trying to get at least the Developer mode working. 
There is no Apps for Android or Iphone available. 
And the following error is while trying to install the npn dependencies:
**npn install** 
npn version is v11.5.0
> 
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
> gyp ERR! System Linux 4.15.0-60-generic
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/carles/Documents/develop/develop_linux/nodejs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/home/carles/Documents/develop/develop_linux/nodejs/WelleAPI-master/node_modules/serialport/build/Release"
> gyp ERR! cwd /home/carles/Documents/develop/develop_linux/nodejs/WelleAPI-master/node_modules/serialport
> gyp ERR! node -v v11.5.0
> gyp ERR! node-gyp -v v5.0.3
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/no
> ...
> ../src/serialport.cpp:174:31: error: no matching function for call to ‘v8::Value::ToInt32()’
>      int fd = argv[1]->ToInt32()->Int32Value();

**Comment by carlesgutierrez** [comment]
Similar issues for Mac Osx

sudo sudo npm install
node ( v10.16.3)
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.16.3 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http EACCES: permission denied, mkdir '/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build' 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release"
gyp ERR! cwd /Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 17.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release' (1)
gyp ERR! configure error stall: info lifecycle serialport@4.0.7~install: Failed
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release"
gyp ERR! cwd /Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN welle_api@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Admin/.npm/_logs/2019-09-20T13_30_36_817Z-debug.log
dude:WelleAPI-master Admin$ gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport/build/Release"
gyp ERR! cwd /Volumes/Data/Develop/nodeJs/WelleAPI-master/node_modules/serialport
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```
